# If you would like to change the commands to something else, this can be done in the commands.yml file.
# View this page for help on adding command aliases: http://wiki.bukkit.org/Commands.yml
name: AdvShop
main: com.empcraft.advshop.AdvShop
version: 0.2.0
author: Empire92
website: www.empcraft.com
depend: [Vault]
commands:
   xpp:
      description: XP trade command.
   db:
      description: AdvShop item data byte command.
   advbuy:
      description: AdvShop buy command.
   advsell:
      description: AdvShop sell command.
   advshop:
      description: AdvShop commands.
   value:
      description: AdvShop value command.
   hand:
      description: AdvShop itemdb command.
   sellall:
      description: AdvShop sellall command.